#!/usr/bin/env python3
"""Convert item icons to Doom palette-indexed C arrays.

Reads WebP icons from assets/items/, resizes to 32x32, quantizes to the
Doom PLAYPAL palette, and outputs a C source file with the icon data.
"""
import os
from PIL import Image

ASSETS_DIR = "/tmp/diablofork/assets/items"
OUTPUT_C = "/tmp/diablofork/src/doom/d_diablo_icons.c"
OUTPUT_H = "/tmp/diablofork/src/doom/d_diablo_icons.h"
PALETTE_RAW = "/tmp/doom_palette.raw"
ICON_SIZE = 32

# Icon name -> filename (without extension).
# One unique icon per item (52 total). Order defines D_ICON_* indices.
ICONS = [
    # Normal (10) - original 8 kept, 2 new boots/gloves
    "sword_short",       # Short Sword
    "armor_leather",     # Leather Armor
    "shield_buckler",    # Buckler
    "helm_cap",          # Cap
    "belt",              # Sash
    "potion_red",        # Healing Potion
    "potion_blue",       # Mana Potion
    "potion_green",      # Rancid Gas Potion
    "boot_leather",      # Leather Boots
    "glove_leather",     # Leather Gloves
    # Magic (8)
    "m_cruel_war_axe",       # Cruel War Axe
    "m_kings_long_sword",    # King's Long Sword
    "m_vampiric_bone_shield",# Vampiric Bone Shield
    "m_prismatic_amulet",    # Prismatic Amulet
    "m_lizards_ring",        # Lizard's Ring
    "m_soldiers_chain_mail", # Soldier's Chain Mail
    "boot_traveler",         # Traveler's Treads
    "glove_assault",         # Assault Gloves
    # Rare (10)
    "r_doombringer",     # Doombringer
    "r_stormlash",       # Stormlash
    "r_soulrender",      # Soulrender
    "r_demonhorn_edge",  # Demonhorn Edge
    "r_nightmare_coil",  # Nightmare Coil
    "r_grimward",        # Grimward
    "r_bloodletter",     # Bloodletter
    "r_fleshrender",     # Fleshrender
    "boot_stormwalker",  # Stormwalkers
    "glove_doom_grasp",  # Doom Grasp
    # Set (10)
    "s_tal_rasha_crest", # Tal Rasha's Horadric Crest
    "s_ik_soul_cage",    # Immortal King's Soul Cage
    "s_trang_oul_guise", # Trang-Oul's Guise
    "s_mavina_sight",    # M'avina's True Sight
    "s_natalya_shadow",  # Natalya's Shadow
    "s_griswold_valor",  # Griswold's Valor
    "s_berserker_hatchet",# Berserker's Hatchet
    "s_sazabi_redeemer", # Sazabi's Cobalt Redeemer
    "boot_ik_pillar",    # Immortal King's Pillar
    "glove_mavina_clutch",# M'avina's Icy Clutch
    # Unique (14)
    "u_stone_of_jordan", # Stone of Jordan
    "u_harlequin_crest", # Harlequin Crest
    "u_grandfather",     # The Grandfather
    "u_windforce",       # Windforce (bow)
    "u_arkaine_valor",   # Arkaine's Valor
    "u_maras_kaleidoscope",# Mara's Kaleidoscope
    "u_bulkathos_band",  # Bul-Kathos' Wedding Band
    "u_titans_revenge",  # Titan's Revenge (javelin)
    "u_lidless_wall",    # Lidless Wall
    "u_vipermagi",       # Skin of the Vipermagi
    "u_thundergod_vigor",# Thundergod's Vigor
    "u_raven_frost",     # Raven Frost
    "boot_war_traveler", # War Traveler
    "glove_frostburn",   # Frostburn
]

def load_palette():
    with open(PALETTE_RAW, "rb") as f:
        data = f.read()
    # List of (r, g, b) tuples
    return [(data[i], data[i+1], data[i+2]) for i in range(0, 768, 3)]

def find_nearest(palette, r, g, b):
    """Find nearest palette index by Euclidean distance."""
    best_idx = 0
    best_dist = float('inf')
    for i, (pr, pg, pb) in enumerate(palette):
        dr = r - pr
        dg = g - pg
        db = b - pb
        dist = dr*dr + dg*dg + db*db
        if dist < best_dist:
            best_dist = dist
            best_idx = i
            if dist == 0:
                break
    return best_idx

def convert_icon(path, palette):
    """Load image, resize to ICON_SIZE, quantize to palette. Returns bytes."""
    img = Image.open(path).convert("RGB")
    img = img.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
    pixels = img.load()
    result = bytearray()
    for y in range(ICON_SIZE):
        for x in range(ICON_SIZE):
            r, g, b = pixels[x, y]
            idx = find_nearest(palette, r, g, b)
            result.append(idx)
    return bytes(result)

def main():
    palette = load_palette()
    print(f"Loaded palette with {len(palette)} colors")

    icon_data = {}
    for name in ICONS:
        path = os.path.join(ASSETS_DIR, name + ".webp")
        if not os.path.exists(path):
            print(f"WARNING: Missing {path}")
            continue
        data = convert_icon(path, palette)
        icon_data[name] = data
        print(f"Converted {name}: {len(data)} bytes")

    # Write C file
    with open(OUTPUT_C, "w") as f:
        f.write("// DiabloDoom item icons - Doom palette-indexed 32x32 pixel data.\n")
        f.write("// Auto-generated by assets/convert_icons.py - DO NOT EDIT.\n\n")
        f.write('#include "d_diablo_icons.h"\n\n')
        f.write(f"#define D_ICON_SIZE {ICON_SIZE}\n\n")

        for i, name in enumerate(ICONS):
            if name not in icon_data:
                continue
            data = icon_data[name]
            f.write(f"// {name}\n")
            f.write(f"static const unsigned char icon_{name}[{ICON_SIZE*ICON_SIZE}] =\n{{\n")
            for y in range(ICON_SIZE):
                f.write("   ")
                for x in range(ICON_SIZE):
                    idx = y * ICON_SIZE + x
                    f.write(f" {data[idx]:3d},")
                f.write("\n")
            f.write("};\n\n")

        f.write("const unsigned char *d_item_icons[] =\n{\n")
        for name in ICONS:
            if name in icon_data:
                f.write(f"    icon_{name},\n")
            else:
                f.write(f"    0, // missing: {name}\n")
        f.write("};\n\n")
        f.write(f"const int d_num_item_icons = {len([n for n in ICONS if n in icon_data])};\n")
        f.write(f"const int d_icon_size = {ICON_SIZE};\n")

    # Write header
    with open(OUTPUT_H, "w") as f:
        f.write("// DiabloDoom item icons - public interface.\n")
        f.write("#ifndef D_DIABLO_ICONS_H\n")
        f.write("#define D_DIABLO_ICONS_H\n\n")
        f.write("// 32x32 palette-indexed icon data, one per entry.\n")
        f.write("extern const unsigned char *d_item_icons[];\n")
        f.write("extern const int d_num_item_icons;\n")
        f.write("extern const int d_icon_size;\n\n")
        f.write("// Icon indices (must match order in d_diablo_icons.c).\n")
        for i, name in enumerate(ICONS):
            f.write(f"#define D_ICON_{name.upper()} {i}\n")
        f.write("\n#endif\n")

    print(f"\nWrote {OUTPUT_C} and {OUTPUT_H}")

if __name__ == "__main__":
    main()
