// DiabloDoom item icons - public interface.
// Auto-generated by assets/convert_icons.py - DO NOT EDIT.
#ifndef D_DIABLO_ICONS_H
#define D_DIABLO_ICONS_H

// 32x32 palette-indexed icon data, one per entry.
extern const unsigned char *d_item_icons[];
extern const int d_num_item_icons;
extern const int d_icon_size;

// Icon indices (must match order in d_diablo_icons.c).
#define D_ICON_GUN_PISTOL 0
#define D_ICON_GUN_SHOTGUN 1
#define D_ICON_GUN_CHAINGUN 2
#define D_ICON_GUN_CHAINSAW 3
#define D_ICON_GUN_ROCKET 4
#define D_ICON_GUN_PLASMA 5
#define D_ICON_GUN_BFG 6
#define D_ICON_GUN_SSG 7
#define D_ICON_AMMO_BOX 8
#define D_ICON_ARMOR_LEATHER 9
#define D_ICON_SHIELD_BUCKLER 10
#define D_ICON_HELM_CAP 11
#define D_ICON_BELT 12
#define D_ICON_POTION_RED 13
#define D_ICON_POTION_BLUE 14
#define D_ICON_POTION_GREEN 15
#define D_ICON_BOOT_LEATHER 16
#define D_ICON_GLOVE_LEATHER 17
#define D_ICON_M_VAMPIRIC_BONE_SHIELD 18
#define D_ICON_M_PRISMATIC_AMULET 19
#define D_ICON_M_LIZARDS_RING 20
#define D_ICON_M_SOLDIERS_CHAIN_MAIL 21
#define D_ICON_BOOT_TRAVELER 22
#define D_ICON_GLOVE_ASSAULT 23
#define D_ICON_R_NIGHTMARE_COIL 24
#define D_ICON_R_GRIMWARD 25
#define D_ICON_BOOT_STORMWALKER 26
#define D_ICON_GLOVE_DOOM_GRASP 27
#define D_ICON_S_TAL_RASHA_CREST 28
#define D_ICON_S_IK_SOUL_CAGE 29
#define D_ICON_S_TRANG_OUL_GUISE 30
#define D_ICON_S_MAVINA_SIGHT 31
#define D_ICON_S_NATALYA_SHADOW 32
#define D_ICON_S_GRISWOLD_VALOR 33
#define D_ICON_BOOT_IK_PILLAR 34
#define D_ICON_GLOVE_MAVINA_CLUTCH 35
#define D_ICON_U_STONE_OF_JORDAN 36
#define D_ICON_U_HARLEQUIN_CREST 37
#define D_ICON_U_ARKAINE_VALOR 38
#define D_ICON_U_MARAS_KALEIDOSCOPE 39
#define D_ICON_U_BULKATHOS_BAND 40
#define D_ICON_U_LIDLESS_WALL 41
#define D_ICON_U_VIPERMAGI 42
#define D_ICON_U_THUNDERGOD_VIGOR 43
#define D_ICON_U_RAVEN_FROST 44
#define D_ICON_BOOT_WAR_TRAVELER 45
#define D_ICON_GLOVE_FROSTBURN 46

#endif
