// DiabloDoom item icons - public interface.
#ifndef D_DIABLO_ICONS_H
#define D_DIABLO_ICONS_H

// 32x32 palette-indexed icon data, one per entry.
extern const unsigned char *d_item_icons[];
extern const int d_num_item_icons;
extern const int d_icon_size;

// Icon indices (must match order in d_diablo_icons.c).
#define D_ICON_SWORD_SHORT 0
#define D_ICON_ARMOR_LEATHER 1
#define D_ICON_SHIELD_BUCKLER 2
#define D_ICON_HELM_CAP 3
#define D_ICON_BELT 4
#define D_ICON_POTION_RED 5
#define D_ICON_POTION_BLUE 6
#define D_ICON_POTION_GREEN 7
#define D_ICON_BOOT_LEATHER 8
#define D_ICON_GLOVE_LEATHER 9
#define D_ICON_M_CRUEL_WAR_AXE 10
#define D_ICON_M_KINGS_LONG_SWORD 11
#define D_ICON_M_VAMPIRIC_BONE_SHIELD 12
#define D_ICON_M_PRISMATIC_AMULET 13
#define D_ICON_M_LIZARDS_RING 14
#define D_ICON_M_SOLDIERS_CHAIN_MAIL 15
#define D_ICON_BOOT_TRAVELER 16
#define D_ICON_GLOVE_ASSAULT 17
#define D_ICON_R_DOOMBRINGER 18
#define D_ICON_R_STORMLASH 19
#define D_ICON_R_SOULRENDER 20
#define D_ICON_R_DEMONHORN_EDGE 21
#define D_ICON_R_NIGHTMARE_COIL 22
#define D_ICON_R_GRIMWARD 23
#define D_ICON_R_BLOODLETTER 24
#define D_ICON_R_FLESHRENDER 25
#define D_ICON_BOOT_STORMWALKER 26
#define D_ICON_GLOVE_DOOM_GRASP 27
#define D_ICON_S_TAL_RASHA_CREST 28
#define D_ICON_S_IK_SOUL_CAGE 29
#define D_ICON_S_TRANG_OUL_GUISE 30
#define D_ICON_S_MAVINA_SIGHT 31
#define D_ICON_S_NATALYA_SHADOW 32
#define D_ICON_S_GRISWOLD_VALOR 33
#define D_ICON_S_BERSERKER_HATCHET 34
#define D_ICON_S_SAZABI_REDEEMER 35
#define D_ICON_BOOT_IK_PILLAR 36
#define D_ICON_GLOVE_MAVINA_CLUTCH 37
#define D_ICON_U_STONE_OF_JORDAN 38
#define D_ICON_U_HARLEQUIN_CREST 39
#define D_ICON_U_GRANDFATHER 40
#define D_ICON_U_WINDFORCE 41
#define D_ICON_U_ARKAINE_VALOR 42
#define D_ICON_U_MARAS_KALEIDOSCOPE 43
#define D_ICON_U_BULKATHOS_BAND 44
#define D_ICON_U_TITANS_REVENGE 45
#define D_ICON_U_LIDLESS_WALL 46
#define D_ICON_U_VIPERMAGI 47
#define D_ICON_U_THUNDERGOD_VIGOR 48
#define D_ICON_U_RAVEN_FROST 49
#define D_ICON_BOOT_WAR_TRAVELER 50
#define D_ICON_GLOVE_FROSTBURN 51

#endif
